-- Equity Award

SELECT (RPTNEED_GROSS_NEED_AMT * .35) - SUM(RPRAWRD_OFFER_AMT)
FROM RPTNEED, RORSTAT, RPRAWRD
WHERE RPRAWRD_AIDY_CODE = RPTNEED_AIDY_CODE
  AND RPRAWRD_PIDM = RPTNEED_PIDM
  AND RPRAWRD_AIDY_CODE = RORSTAT_AIDY_CODE
  AND RPRAWRD_PIDM = RORSTAT_PIDM
  AND RPRAWRD_FUND_CODE IN ('PELL','SEOG','PHEA')
  AND RORSTAT_PGRP_CODE = 'GROUP1'
  AND RPRAWRD_AIDY_CODE = :AIDY
  AND RPRAWRD_PIDM = :PIDM
GROUP BY RPTNEED_GROSS_NEED_AMT