-- Merit Scholarship from Cohort Code

SELECT SUBSTR(SARCHRT_CHRT_CODE, 2)
FROM SARCHRT, SARADAP X
WHERE X.SARADAP_TERM_CODE_ENTRY = SARCHRT_TERM_CODE_ENTRY
  AND X.SARADAP_APPL_NO = SARCHRT_APPL_NO
  AND X.SARADAP_PIDM = SARCHRT_PIDM
  AND X.SARADAP_TERM_CODE_ENTRY =
    (SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM STVTERM, SARADAP Y
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
      AND Y.SARADAP_TERM_CODE_ENTRY = STVTERM_CODE
      AND STVTERM_FA_PROC_YR = :aidy)
  AND SARCHRT_CHRT_CODE LIKE 'P%'
  AND X.SARADAP_PIDM = :pidm